
  // location object
  
{
  id: 100,
  order: '100.00000000000000000000',
  'School Name': 'GB Beau-Bassin Rose-Hill',
  'School Status': { id: 386, value: 'Suspended', color: 'blue' },
  'School Owner': [],
  'Regional Director': null,
  'Gracie Barra Region': [ { id: 5, value: 'GB Europe' } ],
  'Gracie Barra Region (text)': { id: 391, value: 'GB Europe', color: 'green' },
  'Date Added': '2018-12-31',
  Address: 'Windsor Building Royal Road Beau-Bassin Rose-Hill mauritius',
  'Map Address': 'Windsor Building Royal Road Beau-Bassin Rose-Hill, Plaines Wilhems  mauritius',
  'Map Address : Street 1': 'Windsor Building Royal Road',
  'Map Address : Street 2': null,
  'Map Address : City': 'Beau-Bassin Rose-Hill',
  'Map Address : State': { id: 461, value: 'Plaines Wilhems', color: 'blue' },
  'Map Address : Zip': null,
  'Map Address : Country': { id: 799, value: 'mauritius', color: 'blue' },
  'Map Address : Latitude': '-20.159578',
  'Map Address : Longitude': '57.505652',
  'Phone Number': '2307505727',
  'Web Site': 'www.graciebarra.com',
  Professor: 'Goowtamsingh Ramtohul',
  Image: '<img src="https://s3.amazonaws.com/assets.knackhq.com/assets/5bc58e7736d50c7fd1d9406d/63171eb3f0f15107252a6810/original/8x8pixel.png" />',
  'Image : URL': 'https://s3.amazonaws.com/assets.knackhq.com/assets/5bc58e7736d50c7fd1d9406d/63171eb3f0f15107252a6810/original/8x8pixel.png',
  'Premium School': false,
  'SCP Expiration Date Epoch': null,
  'SCP Expiration Date': null,
  'Professor Pic': '<img src="https://s3.amazonaws.com/assets.knackhq.com/assets/5bc58e7736d50c7fd1d9406d/5bc5e4a01d63ea7cc31b43a5/original/8x8pixel.png" />',
  'Professor Pic : URL': 'https://s3.amazonaws.com/assets.knackhq.com/assets/5bc58e7736d50c7fd1d9406d/5bc5e4a01d63ea7cc31b43a5/original/8x8pixel.png',
  'School Region NOT USED': null,
  'Total Registered Students': '0',
  'Total Registered Students Last 7 Days': '0',
  'Total Students That Purchased': '0',
  'Total Purchases Count': null,
  'Student Buy Ratio': { id: 934, value: '0%', color: 'green' },
  'SO Commission All Students': null,
  'SO Commission All Students Last 7 Days': null,
  'Total Commissions Owed': null,
  'Total Commissions Paid': null,
  'Total Valid ICP Certificates': null,
  'Total ICP Enrolled': null,
  'Suspended Date': '2020-04-22',
  'Suspended Reason': 'School in collections, checked with the US on the 23rd April 2020',
  'School Coupon Code Count': '0',
  'Franchise Agreement Expiration': null,
  'Map Filters': { id: 1395, value: 'Standard', color: 'blue' },
  'Has Owner': false,
  'SCP Review Status': null,
  'Most Recent SCP Year': null,
  'SCP Certificates Count': '0',
  'SCP Certificate Link': null,
  'SCP Certificate Preview': null,
  'SCP Certificate Preview : URL': null,
  'School Owner Email': null,
  'PayPal Email': null,
  'Total All Access Passes': '0',
  'Recent Logins': '0',
  'Total Recent Logins': '0',
  'Total Logins Month': null,
  'Facebook URL': null,
  'Instagram URL': null,
  StoreID: null,
  'Covid19 Access': null,
  'Hide Map': null,
  '(default signer) GB Locations to Certificate Signer': null,
  '(unverified/unlocked) Belt Rank Certs': null,
  '(unverified/unlocked) Belt Rank Certs 2': null,
  '(total) Belt Rank Certs': null,
  '(total) Belt Rank Certs 2': null,
  'Student School Subscriptions Select': null,
  'Student School Subscriptions Count': '0',
  'Student School Subscriptions Available': '0',
  'Student Subscription Rate': null,
  'Student Subscription Total Cost': { id: 1411, value: '$0', color: 'blue' },
  Payment: null,
  Country: { id: 1437, value: 'Mauritius', color: 'blue' },
  'Franchise Agreement': null,
  'Franchise Agreement : URL': null,
  'Coupon Codes': [],
  'Coupon Requests': [],
  'Location Ownership Requests': null,
  'School Certifications': [],
  'Certificate Signers': [],
  'SCP Certificates': [],
  'Commission Payments': [],
  'Signature Requests': []
}



//student object
{
  id: 101,
  order: '100.00000000000000000000',
  Student: 'Lilian Ribeiro Lucena',
  'Auto Increment copy': '45360',
  'User ID': '63926dc0e32fc360b81fcc5c',
  Status: { id: 7704, value: 'Active', color: 'blue' },
  'Suspension Reason': '',
  GlobalID: '47360',
  Name: '',
  'Name : Title': '',
  'Name : First': 'Lilian',
  'Name : Middle': '',
  'Name : Last': 'Ribeiro Lucena',
  'Belt Rank': { id: 7707, value: 'Black', color: 'blue' },
  'Belt Rank Number': '5',
  Degree: { id: 7717, value: 'No Degree', color: 'light-blue' },
  'Date of Promotion': '2022-12-08',
  'Belt Rank Verified': { id: 7727, value: 'No', color: 'blue' },
  'Verification Lock': { id: 7730, value: 'No', color: 'blue' },
  'Verified Rank Number': '',
  'Date Joined': '2022-12-08',
  Email: 'lilianlucena11@gmail.com',
  Password: '159357',
  'Gracie Barra Location': 'GB Ponta Pora - MS',
  'Gracie Barra Location Text': '',
  'School Owner (from Gracie Barra Location)': '',
  'Total Spent All Orders': '$85.11',
  'Purchases Count': '1',
  'Free Purchases': '0',
  'SO Total Commission': '$0.00',
  'SO Total Commission Last 7 Days': '',
  'Total ICP Certificates': '0',
  'Valid ICP Certificate': '0',
  'Most Recent ICP Year': '',
  'ICP Enrolled': '0',
  'ICP Expiration Date': null,
  'Joined Site': 'institute.graciebarra.com.br',
  'Covid19 User': '',
  'Terms &amp; Conditions': { id: 7733, value: 'Yes', color: 'blue' },
  'All Access Pass': { id: 7737, value: 'No', color: 'blue' },
  'All Access Date': '',
  'Suspension Date': '',
  'IP Address': '45.187.127.241',
  'Last Login Date': '2022-12-09',
  'Last Login Date / Time': '12/09/2022 4:48am',
  'Logins This Month': '1',
  'Logins Last Month': '0',
  'Belt URL': '<img src="https://gracie-barra.s3-us-west-1.amazonaws.com/Black-Belt-Full.jpg" />',
  'Belt URL : URL': '',
  'Belt Image': '<img src="https://s3.amazonaws.com/assets.knackhq.com/assets/5bc58e7736d50c7fd1d9406d/63a1b1e807a8681ab4a38531/original/blackbeltfull.jpg" />',
  'Belt Image URL': '',
  'Belt Image Attachment': [],
  'Degree URL': '<img src="https://gracie-barra.s3-us-west-1.amazonaws.com/Black-0-Stripe.png" />',
  'Degree URL : URL': '',
  'Long Belt': '<img src="https://s3.amazonaws.com/assets.knackhq.com/assets/5bc58e7736d50c7fd1d9406d/63a1b1e807a8681ab4a3852e/original/black.jpg" />',
  'Long Belt : URL': 'https://s3.amazonaws.com/assets.knackhq.com/assets/5bc58e7736d50c7fd1d9406d/63a1b1e807a8681ab4a3852e/original/black.jpg',
  'Shipping Address': '',
  'Shipping Address : Street 1': '',
  'Shipping Address : Street 2': '',
  'Shipping Address : City': '',
  'Shipping Address : State': '',
  'Shipping Address : Zip': '',
  'Shipping Address : Country': '',
  'Shipping Address : Latitude': '',
  'Shipping Address : Longitude': '',
  'Certificate Signer': 'Adailton Pereira',
  '(unverified) Belt Rank Certs': '0',
  '(unverified) Belt Rank Certs 2': '0',
  '(total) Belt Rank Certs': '0',
  'Verify Rank Text': 'Verify Rank',
  '(total) Belt Rank Certs 2': '0',
  'Are you a GB Student': { id: 7740, value: 'Yes', color: 'blue' },
  'Gracie Barra Region (formula)': 'GB Brasil',
  'Student School Subscriptions Available': '0',
  'Student Has School Subscription': 'No',
  'First Name': 'Lilian',
  'Last Name': 'Ribeiro Lucena',
  'LW Purchases': [],
  'Belt Rank Verification Submissions': '',
  'test link': []
}